version: '2'
services:
  app:
    build: .
    ports:
     - "5001:5001"
    command: python -u app.py
    links:
     - mongo
    depends_on:
     - mongo
    volumes:
     - .:/code
  mongo:
    image: "mongo:latest"
    ports:
     - "27017:27017"
    command: mongod --port 27017