version: "2"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    # command: python -u client_GUI/app.py
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - .:/code
  mongo:
    image: "mongo:latest"
    ports:
      - "27018:27018"
    command: mongod --port 27018
